'use strict';
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const slots=[['DEPUTADO FEDERAL','Deputado federal',4],['DEPUTADO ESTADUAL','Deputado estadual',5],['SENADOR','Senador · 1ª vaga',3],['SENADOR','Senador · 2ª vaga',3],['GOVERNADOR','Governador',2],['PRESIDENTE','Presidente',2]];
const offices=[['DEPUTADO FEDERAL','Dep. federal'],['DEPUTADO ESTADUAL','Dep. estadual'],['SENADOR','Senado'],['GOVERNADOR','Governador'],['PRESIDENTE','Presidente']];
const STATES=[['SP','São Paulo'],['DF','Distrito Federal'],['RJ','Rio de Janeiro'],['MG','Minas Gerais'],['RS','Rio Grande do Sul']];
const candidates=window.CANDIDATOS.candidates, polls=window.PESQUISAS;
const byId=new Map(candidates.map(c=>[c.id,c]));
let uf='SP',office='GOVERNADOR',page=1,choices=Array(6).fill(null),simStep=0,simNumber='',simBlank=false;
try{const savedUf=localStorage.getItem('meu-voto-2026-uf');if(STATES.some(s=>s[0]===savedUf))uf=savedUf;}catch{}
function stateName(code=uf){return (STATES.find(s=>s[0]===code)||['',code])[1];}
function isDistrict(){return uf==='DF';}
function slotOffice(i){return i===1&&isDistrict()?'DEPUTADO DISTRITAL':slots[i][0];}
function slotLabel(i){return i===1&&isDistrict()?'Deputado distrital':slots[i][1];}
function currentOffices(){return offices.map(([o,label])=>o==='DEPUTADO ESTADUAL'&&isDistrict()?['DEPUTADO DISTRITAL','Dep. distrital']:[o,label]);}
function placeOf(c){return c.uf==='BR'?'Brasil':stateName(c.uf);}
function fitsChoice(id,i){if(id===null)return null;if(id==='BRANCO'||id==='NULO')return id;const c=byId.get(id);if(!c||c.office!==slotOffice(i))return false;if(c.office==='PRESIDENTE')return c.uf==='BR'?id:false;return c.uf===uf?id:false;}
function validChoices(v,strict){if(!Array.isArray(v)||v.length!==6)throw Error('Arquivo de escolhas inválido.');return v.map((x,i)=>{const fit=fitsChoice(x,i);if(fit===false){if(strict)throw Error('Candidato incompatível com o cargo ou o estado.');return null;}return fit;});}
try{const saved=localStorage.getItem('meu-voto-2026');if(saved)choices=validChoices(JSON.parse(saved),false);if(choices[2]&&choices[2]===choices[3]&&byId.has(choices[2]))choices[3]=null;}catch{}
function notify(msg){$('#toast').textContent=msg;$('#toast').style.display='block';clearTimeout(notify.timer);notify.timer=setTimeout(()=>$('#toast').style.display='none',4500);}
function persist(){try{localStorage.setItem('meu-voto-2026',JSON.stringify(choices));}catch{notify('Não foi possível salvar no navegador. Use Salvar escolhas.');}renderChoices();}
function digits(number,length){return Array.from({length},(_,i)=>`<span class="digit">${esc(number?.[i]||'')}</span>`).join('');}
function renderChoices(){$('#choices').innerHTML=slots.map((s,i)=>{const x=choices[i],c=byId.get(x);return `<div class="choice"><div class="choice-label"><span>${slotLabel(i)}</span><button data-edit="${i}">${x?'Alterar':'Escolher'}</button></div><div class="digits">${digits(c?.number,s[2])}</div><div class="choice-name">${c?esc(c.name)+' · '+esc(c.party):x||'Ainda não escolhido'}${c&&c.status!=='DEFERIDO'?'<br>Conferir: '+esc(c.status):''}</div>${x?`<button class="remove-choice" data-remove="${i}" style="font-size:11px;padding:2px 6px;margin-top:4px">Remover</button>`:''}</div>`;}).join('');$('#progress').textContent=`${choices.filter(Boolean).length} de 6 escolhas preenchidas · ${stateName()} · salvo neste navegador`;}
function updatePlace(){const name=stateName();$('#brand-scope').textContent='1º TURNO · '+name.toUpperCase();$('#ballot-scope').textContent='04 de outubro · '+name;$('#ballot-order').textContent='A colinha segue a ordem da urna: federal, '+(isDistrict()?'distrital':'estadual')+', dois senadores, governador e presidente.';const summary=$('#location-summary'),text=$('#location-text');if(uf==='SP'){summary.textContent='Título em São Paulo · Residência em São José dos Campos';text.textContent='O recorte de candidatos estaduais é o mesmo para todo o estado de SP. Seu local de votação segue o cadastro eleitoral; morar em São José dos Campos não muda automaticamente sua seção. Se você solicitou e obteve transferência temporária, consulte o local designado.';}else{summary.textContent='Recorte de '+name;text.textContent='Deputado federal, '+(isDistrict()?'deputado distrital':'deputado estadual')+', senador e governador seguem '+name+'. A lista vale para toda a unidade da federação. A Presidência é nacional. Seu local de votação continua o do cadastro eleitoral.';}}
function setView(id){document.querySelectorAll('.view').forEach(el=>el.hidden=el.id!==id);document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===id));}
document.querySelector('nav').addEventListener('click',e=>{if(e.target.dataset.view)setView(e.target.dataset.view);});
function inState(c){if(c.office==='PRESIDENTE')return c.uf==='BR';return c.uf===uf;}
function setOffice(value){office=value;page=1;$('#search').value='';const parties=[...new Set(candidates.filter(c=>c.office===office&&inState(c)).map(c=>c.party))].sort((a,b)=>a.localeCompare(b,'pt-BR'));$('#party').innerHTML='<option value="">Todos os partidos</option>'+parties.map(p=>`<option>${esc(p)}</option>`).join('');$('#office-tabs').innerHTML=currentOffices().map(([o,label])=>`<button data-office="${o}" class="${o===office?'active':''}" aria-pressed="${o===office}">${label}</button>`).join('');renderPolls();renderList();}
function setUf(next){if(!STATES.some(s=>s[0]===next))return;uf=next;try{localStorage.setItem('meu-voto-2026-uf',uf);}catch{}if($('#uf').value!==uf)$('#uf').value=uf;if(office==='DEPUTADO DISTRITAL'&&uf!=='DF')office='DEPUTADO ESTADUAL';if(office==='DEPUTADO ESTADUAL'&&uf==='DF')office='DEPUTADO DISTRITAL';const nextChoices=choices.map((x,i)=>fitsChoice(x,i)||null);const cleared=nextChoices.some((x,i)=>x!==choices[i]);choices=nextChoices;if(choices[2]&&choices[2]===choices[3])choices[3]=null;updatePlace();if(cleared){persist();notify('Escolhas de outro estado foram retiradas da colinha.');}else renderChoices();setOffice(office);}
$('#office-tabs').addEventListener('click',e=>{if(e.target.dataset.office)setOffice(e.target.dataset.office);});
const normalize=s=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
function filtered(){const q=normalize($('#search').value),party=$('#party').value,status=$('#status').value;return candidates.filter(c=>c.office===office&&inState(c)&&(!party||c.party===party)&&(status==='all'||(status==='ballot'?c.inBallot:c.status==='DEFERIDO'&&c.inBallot))&&normalize(c.name+' '+c.fullName+' '+c.number).includes(q)).sort((a,b)=>a.name.localeCompare(b.name,'pt-BR'));}
function renderList(){const rows=filtered(),pages=Math.max(1,Math.ceil(rows.length/16));page=Math.min(page,pages);$('#count').textContent=rows.length+' registros';$('#candidate-list').innerHTML=rows.slice((page-1)*16,page*16).map(c=>`<article class="candidate"><div class="number">${esc(c.number)}</div><div><div class="candidate-name">${esc(c.name)}</div><div class="candidate-meta">${esc(c.party)} · ${esc(placeOf(c))}</div><div class="candidate-status ${c.status!=='DEFERIDO'?'warn':''}">${esc(c.status)} · Destinação: ${esc(c.voteDestination)}${!c.inBallot?' · Fora da urna':''}</div></div><div class="candidate-actions"><a href="${esc(c.source)}" target="_blank" rel="noopener">TSE</a><button data-pick="${c.id}">Escolher</button></div></article>`).join('')||'<p class="empty">Nenhum candidato encontrado com estes filtros.</p>';$('#pagination').innerHTML=`<button id="prev" ${page===1?'disabled':''}>Anterior</button><span>Página ${page} de ${pages}</span><button id="next" ${page===pages?'disabled':''}>Próxima</button>`;$('#prev').onclick=()=>{page--;renderList();};$('#next').onclick=()=>{page++;renderList();};}
['search','party','status'].forEach(id=>$('#'+id).addEventListener(id==='search'?'input':'change',()=>{page=1;renderList();}));
function pollMatches(p){if(p.office!==office)return false;if(p.office==='PRESIDENTE'||/brasil/i.test(p.region))return true;return uf==='SP'&&/s[aã]o paulo/i.test(p.region);}
function renderPolls(){const ps=polls.filter(pollMatches);$('#poll-title').textContent=currentOffices().find(o=>o[0]===office)[1];if(!ps.length){$('#poll-content').innerHTML='<div class="empty"><strong>Sem pesquisa cadastrada para este cargo.</strong><p>Consulte os candidatos abaixo. Ausência de dados não significa 0% de intenção de voto.</p></div>';return;}$('#poll-content').innerHTML='<label>Levantamento<select id="poll-select">'+ps.map(p=>`<option value="${p.id}">${p.institute} · ${p.published.split('-').reverse().join('/')} · ${p.region}</option>`).join('')+'</select></label><div id="poll-detail"></div>';$('#poll-select').onchange=()=>renderPoll(polls.find(p=>p.id===$('#poll-select').value));renderPoll(ps[0]);}
function renderPoll(p){const actual=p.results.filter(r=>r[1]!==null),other=p.results.filter(r=>r[1]===null);$('#poll-detail').innerHTML=`<div class="metadata">Coleta: ${esc(p.field)} · ${p.sample.toLocaleString('pt-BR')} entrevistas<br>Margem geral: ±${p.margin} p.p. · Confiança: ${p.confidence}% · ${esc(p.registration)}<br>${esc(p.method)} · Contratante: ${esc(p.sponsor)}</div><div class="poll-rows">${actual.map(r=>`<div class="bar-row"><span class="bar-label">${esc(r[0])}</span><div class="bar-track"><div class="bar" style="width:${r[2]}%"></div><span class="error-range" style="left:${Math.max(0,r[2]-p.margin)}%;width:${Math.min(100,r[2]+p.margin)-Math.max(0,r[2]-p.margin)}%" title="Faixa ilustrativa: percentual ± margem geral"></span></div><strong>${r[2]}%</strong></div>`).join('')}</div><p class="metadata">${other.map(r=>`${esc(r[0])}: <strong>${r[2]}%</strong>`).join(' · ')}</p><p class="fine">Escala fixa de 0 a 100%. Marcas indicam ± margem geral, como referência. Percentuais arredondados.</p><p class="poll-note">${esc(p.note)}</p><p class="fine">Levantamento selecionado; sem atualização automática. <a href="${p.source}" target="_blank" rel="noopener">Resultados e metodologia</a> · <a href="${p.primary}" target="_blank" rel="noopener">Página do instituto</a></p>`;}
function choose(id,slot){const c=byId.get(id);if(c&&(c.office!==slotOffice(slot)||(c.office==='PRESIDENTE'?c.uf!=='BR':c.uf!==uf)))return false;if(c&&slot>=2&&slot<=3&&choices[slot===2?3:2]===id){notify('Escolha dois senadores diferentes.');return false;}choices[slot]=id;persist();return true;}
function showPick(id){const c=byId.get(id);$('#pick-title').textContent=c.name;$('#pick-info').textContent=`${c.party} · ${c.number} · ${c.status}. Destinação dos votos: ${c.voteDestination}. ${!c.inBallot?'Este registro não consta na urna.':''}`;const allowed=c.inBallot&&!['RENÚNCIA','INDEFERIDO','PEDIDO NÃO CONHECIDO'].includes(c.status);$('#pick-actions').innerHTML=allowed?slots.map((s,i)=>slotOffice(i)===c.office?`<button class="primary" data-slot="${i}">${c.status==='DEFERIDO'?'Escolher':'Ciente da situação: escolher'} ${c.office==='SENADOR'?i===2?'1ª vaga':'2ª vaga':''}</button>`:'').join(''):'<p>Este registro está preservado para consulta, mas não está disponível para preencher a colinha.</p>';$('#pick-actions').onclick=e=>{if(e.target.dataset.slot!==undefined&&choose(id,Number(e.target.dataset.slot))){$('#pick-dialog').close();notify('Colinha atualizada.');}};$('#pick-dialog').showModal();}
$('#candidate-list').addEventListener('click',e=>{if(e.target.dataset.pick)showPick(e.target.dataset.pick);});
$('#choices').addEventListener('click',e=>{if(e.target.dataset.remove!==undefined){choices[Number(e.target.dataset.remove)]=null;persist();}if(e.target.dataset.edit!==undefined){setView('explorar');setOffice(slotOffice(Number(e.target.dataset.edit)));$('#search').focus();}});
function printBallot(){window.print();notify('Se a janela não abrir, baixe a colinha e imprima no seu navegador habitual.');}$('#print').onclick=printBallot;$('#print-top').onclick=printBallot;
$('#download-ballot').onclick=()=>{const content=slots.map((s,i)=>{const c=byId.get(choices[i]);return `<section><h2>${slotLabel(i)}</h2><div class="digits">${digits(c?.number,s[2])}</div><p>${c?esc(c.name)+' · '+esc(c.party):choices[i]||'Ainda não escolhido'}${c&&c.status!=='DEFERIDO'?'<br>Conferir: '+esc(c.status):''}</p></section>`;}).join('');const html=`<!doctype html><html lang="pt-BR"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Minha colinha — 2026</title><style>body{font:16px Arial,sans-serif;color:#152d4a;margin:25px}main{width:81mm;border:1px dashed #777;padding:7mm}h1{font-size:25px;margin:0}h2{font-size:14px;text-transform:uppercase;margin:10px 0 6px}p{font-size:12px;margin:5px 0}section{padding:7px 0;border-bottom:1px solid #ddd}.digits{display:flex;gap:5px}.digit{width:8mm;height:9mm;display:inline-flex;align-items:center;justify-content:center;border:1px solid #777;font-size:25px;font-weight:bold}footer{margin-top:14px;font-size:11px}button{padding:12px;margin-bottom:15px}@page{size:A4;margin:15mm}@media print{body{margin:0}button{display:none}main{break-inside:avoid}}</style><button onclick="window.print()">Imprimir / salvar PDF</button><main><h1>Colinha eleitoral 2026</h1><p>1º turno · 04 de outubro · ${esc(stateName())}</p>${content}<footer>Leve em papel. Material pessoal, sem vínculo com o TSE.</footer></main></html>`;const a=document.createElement('a'),url=URL.createObjectURL(new Blob([html],{type:'text/html;charset=utf-8'}));a.href=url;a.download='minha-colinha-2026.html';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
function download(name,data){const a=document.createElement('a'),url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
$('#export').onclick=()=>download('minha-colinha-2026.json',{version:1,uf,choices,exported:new Date().toISOString()});
$('#import').onchange=async e=>{try{const f=e.target.files[0];if(!f)return;if(f.size>100000)throw Error('Arquivo muito grande.');const obj=JSON.parse(await f.text());if(obj.version!==1)throw Error('Versão de arquivo inválida.');if(STATES.some(s=>s[0]===obj.uf))uf=obj.uf;else{const sample=(obj.choices||[]).map(id=>byId.get(id)).find(c=>c&&c.uf!=='BR');if(sample)uf=sample.uf;}if(office==='DEPUTADO DISTRITAL'&&uf!=='DF')office='DEPUTADO ESTADUAL';if(office==='DEPUTADO ESTADUAL'&&uf==='DF')office='DEPUTADO DISTRITAL';const v=validChoices(obj.choices,true);if(v[2]&&v[2]===v[3]&&byId.has(v[2]))throw Error('Os dois senadores devem ser diferentes.');choices=v;try{localStorage.setItem('meu-voto-2026-uf',uf);}catch{}$('#uf').value=uf;updatePlace();persist();setOffice(office);notify('Escolhas restauradas.');}catch(err){notify(err.message||'Não foi possível ler o arquivo.');}e.target.value='';};
function matchSim(){return candidates.filter(c=>c.office===slotOffice(simStep)&&inState(c)&&c.number===simNumber&&c.inBallot&&!['RENÚNCIA','INDEFERIDO','PEDIDO NÃO CONHECIDO'].includes(c.status));}
function renderSim(){$('#sim-step').textContent=simStep<6?`Voto ${simStep+1} de 6`:'Treino concluído';$('#sim-office').textContent=simStep<6?slotLabel(simStep):'FIM';$('#sim-digits').innerHTML=simStep<6?digits(simNumber,slots[simStep][2]):'';let txt='Digite o número no teclado ao lado.';if(simStep===6)txt='Suas escolhas estão na colinha. Você pode revisá-las antes de imprimir.';else if(simBlank)txt='VOTO EM BRANCO';else if(simNumber.length===slots[simStep][2]){const m=matchSim();txt=m.length===1?`${m[0].name} · ${m[0].party} · ${m[0].status}`:m.length>1?'Número com mais de um registro. Confira a lista e o TSE.':'Número não encontrado entre os registros disponíveis. Confirmar produzirá NULO neste treino.';}$('#sim-candidate').textContent=txt;$('#confirm').disabled=simStep===6||(!simBlank&&simNumber.length!==slots[simStep][2]);}
$('#keypad').innerHTML=[1,2,3,4,5,6,7,8,9,0].map(n=>`<button data-digit="${n}">${n}</button>`).join('');$('#keypad').onclick=e=>{if(e.target.dataset.digit!==undefined&&simStep<6){simBlank=false;if(simNumber.length<slots[simStep][2])simNumber+=e.target.dataset.digit;$('#sim-feedback').textContent='';renderSim();}};$('#blank').onclick=()=>{if(simStep<6){simBlank=true;simNumber='';renderSim();}};$('#correct').onclick=()=>{simNumber='';simBlank=false;$('#sim-feedback').textContent='';renderSim();};$('#confirm').onclick=()=>{if(simStep>=6||$('#confirm').disabled)return;const m=matchSim();if(!simBlank&&m.length>1){$('#sim-feedback').textContent='Confira os registros antes de confirmar.';return;}const value=simBlank?'BRANCO':m[0]?.id||'NULO';if(choose(value,simStep)){simStep++;simNumber='';simBlank=false;renderSim();}};$('#restart').onclick=()=>{simStep=0;simNumber='';simBlank=false;$('#sim-feedback').textContent='';renderSim();};
$('#sources').innerHTML=`<div class="source"><strong>Candidaturas e situação · TSE</strong><p>${candidates.length.toLocaleString('pt-BR')} registros de SP, DF, RJ, MG, RS e Presidência. Base gerada em ${esc(candidates[0].generated)}; consulta em 01/10/2026. Junção por identificador de candidatura. Preservamos registros fora da urna e situações com recurso. As pesquisas de governo e Senado cadastradas são de São Paulo; nos demais estados, a Presidência continua disponível.</p><a href="${window.CANDIDATOS.source}" target="_blank" rel="noopener">Portal de Dados Abertos do TSE</a></div>`+polls.map(p=>`<div class="source"><strong>${p.institute} · ${p.office} · ${p.published.split('-').reverse().join('/')}</strong><p>${p.registration} · ${p.region} · ${p.sample} entrevistas · ±${p.margin} p.p. · ${p.confidence}% de confiança.</p><a href="${p.source}" target="_blank" rel="noopener">Resultados publicados</a> · <a href="${p.primary}" target="_blank" rel="noopener">Instituto</a></div>`).join('')+'<div class="source"><a target="_blank" rel="noopener" href="https://www.tse.jus.br/comunicacao/noticias/2026/Marco/eleicoes-2026-conheca-a-ordem-de-votacao-na-urna-eletronica">Ordem dos cargos · TSE</a> · <a target="_blank" rel="noopener" href="https://www.tse.jus.br/eleicoes/simulador-de-votacao">Simulador de referência</a></div>';
function downloadInstagram(){const W=1080,H=1350,canvas=document.createElement('canvas');canvas.width=W;canvas.height=H;const x=canvas.getContext('2d');x.fillStyle='#234f83';x.fillRect(0,0,W,H);x.fillStyle='#ffcf4b';x.fillRect(64,62,118,118);x.fillStyle='#122b4b';x.font='900 58px Arial';x.textAlign='center';x.fillText('26',123,139);x.textAlign='left';x.fillStyle='#fff';x.font='700 46px Arial';x.fillText('MINHA COLINHA',64,260);x.fillStyle='#ffcf4b';x.font='700 66px Arial';x.fillText('1º TURNO 2026',64,335);x.fillStyle='#e5eef9';x.font='28px Arial';x.fillText('04 de outubro · '+stateName(),64,385);x.fillStyle='#fff';if(x.roundRect)x.roundRect(48,430,984,780,28);else x.rect(48,430,984,780);x.fill();const labels=['DEPUTADO FEDERAL',isDistrict()?'DEPUTADO DISTRITAL':'DEPUTADO ESTADUAL','SENADOR · 1ª VAGA','SENADOR · 2ª VAGA','GOVERNADOR','PRESIDENTE'];const ys=[488,600,712,824,936,1048];labels.forEach((label,i)=>{const c=byId.get(choices[i]);x.fillStyle='#122b4b';x.font='700 25px Arial';x.fillText(label,82,ys[i]);const n=c?.number||'';for(let j=0;j<slots[i][2];j++){x.strokeStyle='#aebdce';x.lineWidth=2;x.strokeRect(82+j*65,ys[i]+23,54,59);x.fillStyle='#122b4b';x.font='700 38px Arial';x.textAlign='center';x.fillText(n[j]||'',109+j*65,ys[i]+64);x.textAlign='left';}x.fillStyle=c?'#425a73':'#78899b';x.font='22px Arial';x.fillText(c?`${c.name} · ${c.party}`:'Ainda não escolhido',82,ys[i]+112);});x.fillStyle='#e5eef9';x.font='22px Arial';x.fillText('Material pessoal · sem vínculo com o TSE',64,1288);canvas.toBlob(blob=>{const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='minha-colinha-instagram-1080x1350.png';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);notify('PNG 1080×1350 baixado: formato vertical 4:5 para o feed do Instagram.');},'image/png');}
downloadInstagram=function(){const W=1080,H=1350,canvas=document.createElement('canvas');canvas.width=W;canvas.height=H;const x=canvas.getContext('2d');x.fillStyle='#234f83';x.fillRect(0,0,W,H);x.fillStyle='#ffcf4b';x.fillRect(64,62,118,118);x.fillStyle='#122b4b';x.font='900 58px Arial';x.textAlign='center';x.fillText('26',123,139);x.textAlign='left';x.fillStyle='#fff';x.font='700 46px Arial';x.fillText('MINHA COLINHA',64,260);x.fillStyle='#ffcf4b';x.font='700 66px Arial';x.fillText('1º TURNO 2026',64,335);x.fillStyle='#e5eef9';x.font='28px Arial';x.fillText('04 de outubro · '+stateName(),64,385);x.fillStyle='#fff';if(x.roundRect)x.roundRect(48,430,984,780,28);else x.rect(48,430,984,780);x.fill();const labels=['DEPUTADO FEDERAL',isDistrict()?'DEPUTADO DISTRITAL':'DEPUTADO ESTADUAL','SENADOR · 1ª VAGA','SENADOR · 2ª VAGA','GOVERNADOR','PRESIDENTE'],ys=[480,600,720,840,960,1080];labels.forEach((label,i)=>{const c=byId.get(choices[i]);x.fillStyle='#122b4b';x.font='700 25px Arial';x.fillText(label,82,ys[i]);const n=c?.number||'';for(let j=0;j<slots[i][2];j++){x.strokeStyle='#aebdce';x.lineWidth=2;x.strokeRect(82+j*65,ys[i]+23,54,59);x.fillStyle='#122b4b';x.font='700 38px Arial';x.textAlign='center';x.fillText(n[j]||'',109+j*65,ys[i]+64);x.textAlign='left';}x.fillStyle=c?'#425a73':'#78899b';x.font='22px Arial';x.fillText(c?`${c.name} · ${c.party}`:'Ainda não escolhido',82,ys[i]+100);});x.fillStyle='#e5eef9';x.font='22px Arial';x.fillText('Material pessoal · sem vínculo com o TSE',64,1288);canvas.toBlob(blob=>{const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='minha-colinha-instagram-1080x1350.png';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);notify('PNG 1080×1350 baixado: formato vertical 4:5 para o feed do Instagram.');},'image/png');};const instagramButton=document.createElement('button');instagramButton.className='primary';instagramButton.id='download-instagram';instagramButton.style.gridColumn='1/-1';instagramButton.textContent='Baixar para Instagram · PNG 1080×1350';instagramButton.onclick=downloadInstagram;$('#download-ballot').after(instagramButton);
$('#uf').value=uf;$('#uf').addEventListener('change',()=>setUf($('#uf').value));updatePlace();renderChoices();setOffice(office);renderSim();
function downloadInstagramV2(){const W=1080,H=1350,canvas=document.createElement('canvas');canvas.width=W;canvas.height=H;const x=canvas.getContext('2d');x.fillStyle='#234f83';x.fillRect(0,0,W,H);x.fillStyle='#ffcf4b';x.fillRect(64,62,118,118);x.fillStyle='#122b4b';x.font='900 58px Arial';x.textAlign='center';x.fillText('26',123,139);x.textAlign='left';x.fillStyle='#fff';x.font='700 46px Arial';x.fillText('MINHA COLINHA',64,260);x.fillStyle='#ffcf4b';x.font='700 66px Arial';x.fillText('1º TURNO 2026',64,335);x.fillStyle='#e5eef9';x.font='28px Arial';x.fillText('04 de outubro · '+stateName(),64,385);x.fillStyle='#fff';if(x.roundRect)x.roundRect(48,430,984,780,28);else x.rect(48,430,984,780);x.fill();const labels=['DEPUTADO FEDERAL',isDistrict()?'DEPUTADO DISTRITAL':'DEPUTADO ESTADUAL','SENADOR · 1ª VAGA','SENADOR · 2ª VAGA','GOVERNADOR','PRESIDENTE'],ys=[480,600,720,840,960,1080];labels.forEach((label,i)=>{const c=byId.get(choices[i]),n=c?.number||'',count=slots[i][2],box=68,gap=10,total=count*box+(count-1)*gap,left=970-total;x.fillStyle='#122b4b';x.textAlign='left';x.font='700 25px Arial';x.fillText(label,82,ys[i]);x.fillStyle=c?'#425a73':'#78899b';x.font='22px Arial';let name=c?`${c.name} · ${c.party}`:choices[i]||'Ainda não escolhido';if(name.length>34)name=name.slice(0,33)+'…';x.fillText(name,82,ys[i]+38);for(let j=0;j<count;j++){const bx=left+j*(box+gap);x.strokeStyle='#8fa7c2';x.lineWidth=3;x.strokeRect(bx,ys[i]-4,box,78);x.fillStyle='#122b4b';x.font='700 50px Arial';x.textAlign='center';x.fillText(n[j]||'',bx+box/2,ys[i]+53);}x.textAlign='left';});x.fillStyle='#e5eef9';x.font='22px Arial';x.fillText('Material pessoal · sem vínculo com o TSE',64,1288);canvas.toBlob(blob=>{const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='minha-colinha-instagram-1080x1350.png';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);notify('PNG 1080×1350 baixado com números destacados à direita.');},'image/png');}
instagramButton.onclick=downloadInstagramV2;
